import {useState} from 'react';
import {Plus,Trash2,X} from 'lucide-react';
import type {AddonGroup,Product,ProductOptionItem} from '../../models';
import {addonService} from '../../services/addonService';
import {productService} from '../../services/productService';
import {Input} from '../../components/common/Input';
import {Button} from '../../components/common/Button';
import {Toggle} from '../../components/common/Toggle';
import {formatCurrency} from '../../utils/format';
const newItem=():ProductOptionItem=>({id:crypto.randomUUID(),name:'',price:0,available:true});
export function AddonsPage(){
 const[,refresh]=useState(0);const[selected,setSelected]=useState<Product|null>(null);const[items,setItems]=useState<ProductOptionItem[]>([]);const[max,setMax]=useState(3);
 const products=productService.getAll();
 function open(product:Product){const existing=addonService.getForProduct(product.id)[0];setSelected(product);setItems(existing?.items.map(x=>({...x}))||[newItem()]);setMax(existing?.maxSelections||3)}
 function close(){setSelected(null);setItems([])}
 function save(){if(!selected)return;const clean=items.filter(i=>i.name.trim());if(!clean.length)return alert('Adicione pelo menos um adicional.');const all=addonService.getAll();const detached=all.map(g=>({...g,applicableProductIds:g.applicableProductIds.filter(id=>id!==selected.id)})).filter(g=>g.applicableProductIds.length>0);addonService.save(detached);const data:Omit<AddonGroup,'id'>={name:`Adicionais de ${selected.name}`,required:false,maxSelections:max,active:true,applicableProductIds:[selected.id],items:clean};addonService.create(data);close();refresh(x=>x+1)}
 return <div><div><h1 className="text-3xl font-black">Adicionais por produto</h1><p className="mt-1 text-slate-500">Ative ou desative itens no cardápio e clique em um produto para configurar seus adicionais.</p></div>
 <div className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{products.map(p=>{const groups=addonService.getForProduct(p.id);const total=groups.reduce((sum,g)=>sum+g.items.length,0);return <article key={p.id} onClick={()=>open(p)} className="cursor-pointer overflow-hidden rounded-2xl border bg-white shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"><img src={p.imageUrl} alt={p.name} className="aspect-[16/9] w-full object-cover"/><div className="p-4"><div className="flex items-start justify-between gap-3"><div><h2 className="font-black">{p.name}</h2><p className="mt-1 text-sm text-slate-500">{total} adicional(is) configurado(s)</p></div><div onClick={e=>e.stopPropagation()}><Toggle checked={p.available} labelOn="No cardápio" labelOff="Oculto" onChange={()=>{productService.toggleAvailability(p.id);refresh(x=>x+1)}}/></div></div><button className="mt-4 w-full rounded-xl border py-2 text-sm font-bold" style={{color:'var(--primary)',borderColor:'var(--primary)'}}>Configurar adicionais</button></div></article>})}</div>
 {selected&&<div className="fixed inset-0 z-50 flex items-end justify-center bg-black/55 sm:items-center sm:p-4" onMouseDown={e=>e.target===e.currentTarget&&close()}><div className="max-h-[92vh] w-full overflow-y-auto rounded-t-3xl bg-white sm:max-w-2xl sm:rounded-3xl"><div className="sticky top-0 z-10 flex items-center justify-between border-b bg-white p-5"><div><h2 className="text-xl font-black">Adicionais de {selected.name}</h2><p className="text-sm text-slate-500">Configure nome, preço e disponibilidade.</p></div><button onClick={close} className="rounded-full bg-slate-100 p-2"><X/></button></div><div className="space-y-5 p-5"><label className="block"><span className="mb-2 block font-bold">Máximo de escolhas</span><Input type="number" min="1" value={max} onChange={e=>setMax(Math.max(1,Number(e.target.value)))}/></label><section><div className="flex items-center justify-between"><b>Opções</b><button type="button" onClick={()=>setItems([...items,newItem()])} className="flex items-center gap-1 text-sm font-bold" style={{color:'var(--primary)'}}><Plus size={17}/>Adicionar</button></div><div className="mt-3 space-y-3">{items.map((item,index)=><div key={item.id} className="grid gap-2 rounded-xl border p-3 sm:grid-cols-[1fr_150px_auto_auto]"><Input placeholder="Nome do adicional" value={item.name} onChange={e=>setItems(items.map((x,i)=>i===index?{...x,name:e.target.value}:x))}/><Input type="number" step="0.01" min="0" placeholder="Valor" value={item.price} onChange={e=>setItems(items.map((x,i)=>i===index?{...x,price:Number(e.target.value)}:x))}/><Toggle checked={item.available} onChange={()=>setItems(items.map((x,i)=>i===index?{...x,available:!x.available}:x))}/><button onClick={()=>setItems(items.filter((_,i)=>i!==index))} className="rounded-xl p-2 text-red-600"><Trash2/></button>{item.name&&<small className="sm:col-span-4 text-slate-500">Será exibido por {formatCurrency(item.price)}.</small>}</div>)}</div></section><Button className="w-full" onClick={save}>Salvar adicionais deste produto</Button></div></div></div>}</div>;
}
